---
- name: 'Disable and stop all cloud-init services'
  become: true
  ansible.builtin.service:
    name: "{{ service }}"
    state: 'stopped'
    enabled: 'false'
  loop: "{{ cloud_init_services }}"
  loop_control:
    loop_var: service
  when:
    - ansible_facts.services["snapd.service"].state == 'running'
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version >= "22.04"
    - server_services.services[service] is defined
    - server_services.services[service].status == 'enabled'

- name: 'Check if /etc/cloud/ exists'
  become: true
  ansible.builtin.stat:
    path: /etc/cloud/
  register: etc_cloud_folder

- name: 'Generate /etc/cloud/cloud-init.disabled'
  become: true
  ansible.builtin.copy:
    dest: '/etc/cloud/cloud-init.disabled'
    content: 'disabled by ansible\n'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: etc_cloud_folder.stat.exists
